version: "3.9"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/appdb
      - JWT_SECRET=supersecret
      - PEPPER=some_pepper
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    depends_on:
      - backend
      - db
    ports:
      - "8080:80"

volumes:
  db_data:
